// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StellarImperiums.Infrastructure.Persistence;

#nullable disable

namespace StellarImperiums.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StellarDbContext))]
    partial class StellarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StellarImperiums.Domain.Utilisateurs.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_utilisateur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DateInscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_inscription")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("DerniereConnexion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("derniere_connexion");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mail");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mot_de_passe");

                    b.Property<bool>("NecessaireAModifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("necessaire_a_modifier");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pseudo");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reset_token");

                    b.Property<DateTimeOffset?>("ResetTokenExpireLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reset_token_expire_le");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<bool>("Suspendu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("suspendu");

                    b.HasKey("Id");

                    b.HasIndex("DateInscription")
                        .IsDescending()
                        .HasDatabaseName("idx_utilisateur_date_inscription");

                    b.HasIndex("Mail")
                        .IsUnique()
                        .HasDatabaseName("utilisateur_mail_key");

                    b.HasIndex("Pseudo")
                        .IsUnique()
                        .HasDatabaseName("utilisateur_pseudo_key");

                    b.HasIndex("ResetToken")
                        .IsUnique()
                        .HasDatabaseName("idx_utilisateur_reset_token")
                        .HasFilter("\"reset_token\" IS NOT NULL");

                    b.HasIndex("Role")
                        .HasDatabaseName("idx_utilisateur_role");

                    b.ToTable("utilisateur", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
