<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\StellarImperiums.Domain\StellarImperiums.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx" Version="6.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
